from __future__ import annotations

import hashlib
import os
from typing import Any

from flask import Flask, jsonify, request

from audit import (
    latest_certificate_for_creator,
    new_id,
    read_appeals,
    read_audit_events,
    read_certificates,
    save_appeal,
    save_certificate,
    utc_now,
    write_audit_event,
)
from detector import classify_content
from home_repair import assess_home_repair_question
from multimodal import analyze_image_metadata
from rate_limit import SlidingWindowRateLimiter


MAX_CONTENT_CHARS = 20_000
LABEL_COPY = {
    "likely_ai_generated": (
        "Our system found strong indicators that this content may have been generated by an AI writing tool. "
        "This is not a final accusation and no creator penalty should be applied without review. "
        "If you wrote this yourself, submit an appeal with context about your drafting process."
    ),
    "uncertain": (
        "Our system was not able to confidently determine whether this content was written by a person or an AI tool. "
        "No automated action should be taken. A human reviewer should consider the context before applying a label."
    ),
    "likely_human_written": (
        "Our system found stronger indicators that this content was written by a person. "
        "No AI-generated content label is recommended."
    ),
}
INDEX_HTML = """
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Provenance Guard</title>
  <style>
    :root {
      color-scheme: light;
      --ink: #17212b;
      --muted: #5f6b78;
      --line: #d7dde3;
      --panel: #ffffff;
      --page: #f6f8fa;
      --accent: #176b87;
      --accent-dark: #0f4f66;
      --warn: #a45c10;
      --ok: #236b3a;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--page);
      color: var(--ink);
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.45;
    }
    header {
      background: #10212b;
      color: #fff;
      padding: 20px 28px;
      border-bottom: 4px solid var(--accent);
    }
    h1, h2, h3, p { margin: 0; }
    h1 { font-size: 28px; font-weight: 750; letter-spacing: 0; }
    header p { margin-top: 6px; color: #c9d8df; max-width: 900px; }
    main {
      max-width: 1280px;
      margin: 0 auto;
      padding: 22px;
      display: grid;
      grid-template-columns: minmax(0, 1.15fr) minmax(360px, 0.85fr);
      gap: 18px;
    }
    section, aside {
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 18px;
    }
    .stack { display: grid; gap: 16px; }
    .row {
      display: grid;
      grid-template-columns: repeat(2, minmax(0, 1fr));
      gap: 12px;
    }
    label {
      display: grid;
      gap: 6px;
      color: var(--muted);
      font-size: 13px;
      font-weight: 650;
    }
    input, textarea {
      width: 100%;
      border: 1px solid #c8d0d8;
      border-radius: 6px;
      padding: 10px 12px;
      color: var(--ink);
      background: #fff;
      font: inherit;
    }
    textarea { min-height: 180px; resize: vertical; }
    button {
      border: 0;
      border-radius: 6px;
      background: var(--accent);
      color: #fff;
      padding: 10px 14px;
      font: inherit;
      font-weight: 700;
      cursor: pointer;
    }
    button:hover { background: var(--accent-dark); }
    button.secondary {
      background: #e8edf1;
      color: #1f2d38;
    }
    button.secondary:hover { background: #dce4ea; }
    .actions { display: flex; flex-wrap: wrap; gap: 10px; align-items: center; }
    .result {
      min-height: 180px;
      white-space: pre-wrap;
      overflow-wrap: anywhere;
      border: 1px solid var(--line);
      border-radius: 8px;
      background: #fbfcfd;
      padding: 14px;
      color: #26333e;
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
      font-size: 13px;
    }
    .status {
      display: inline-flex;
      align-items: center;
      min-height: 30px;
      border-radius: 999px;
      padding: 4px 10px;
      background: #e9f5ef;
      color: var(--ok);
      font-size: 13px;
      font-weight: 700;
    }
    .metric-grid {
      display: grid;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 10px;
      margin-top: 12px;
    }
    .metric {
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 12px;
      background: #fbfcfd;
    }
    .metric strong {
      display: block;
      font-size: 12px;
      color: var(--muted);
      margin-bottom: 4px;
    }
    .metric span { font-size: 20px; font-weight: 760; }
    .warning { color: var(--warn); font-weight: 700; }
    .small { color: var(--muted); font-size: 13px; }
    .flow {
      display: grid;
      grid-template-columns: repeat(5, minmax(0, 1fr));
      gap: 8px;
      margin-top: 12px;
    }
    .flow div {
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 10px;
      background: #fbfcfd;
      color: #33414d;
      font-size: 13px;
      font-weight: 700;
      text-align: center;
    }
    @media (max-width: 860px) {
      main { grid-template-columns: 1fr; padding: 14px; }
      header { padding: 18px; }
      .row, .metric-grid, .flow { grid-template-columns: 1fr; }
    }
  </style>
</head>
<body>
  <header>
    <h1>Provenance Guard</h1>
    <p>Classify submitted content, communicate uncertainty, log decisions, and route contested labels into an appeal workflow.</p>
  </header>
  <main>
    <div class="stack">
      <section>
        <h2>How a Decision Moves Through the System</h2>
        <div class="flow">
          <div>Submit</div>
          <div>Signals</div>
          <div>Confidence</div>
          <div>Label</div>
          <div>Audit / Appeal</div>
        </div>
      </section>

      <section>
        <h2>Content Classification</h2>
        <p class="small">Paste submitted content and run the multi-signal authorship guardrail.</p>
        <div class="row" style="margin-top: 14px;">
          <label>Creator ID
            <input id="creatorId" value="creator_demo">
          </label>
          <label>Content ID
            <input id="contentId" value="post_demo">
          </label>
        </div>
        <label style="margin-top: 12px;">Submitted Content
          <textarea id="content">Furthermore, it is important to note that a robust and seamless platform can leverage modern workflows. Moreover, the solution provides a structured approach for teams seeking consistent outcomes. Additionally, the process can be adapted across contexts while maintaining clarity and efficiency. In conclusion, this comprehensive method supports scalable collaboration and measurable improvements.</textarea>
        </label>
        <div class="actions" style="margin-top: 12px;">
          <button id="classifyBtn">Classify</button>
          <button class="secondary" id="auditBtn">Refresh Audit</button>
          <span class="status" id="health">Checking API...</span>
          <span class="status" id="auditStatus">Audit not loaded</span>
        </div>
      </section>

      <section>
        <h2>Verified Human Certificate</h2>
        <p class="small">Issue a creator-level credential after a human verification step.</p>
        <div class="row" style="margin-top: 14px;">
          <label>Creator ID
            <input id="certCreatorId" value="creator_demo">
          </label>
          <label>Verification Method
            <input id="certMethod" value="draft history + profile review">
          </label>
        </div>
        <label style="margin-top: 12px;">Evidence Summary
          <input id="certEvidence" value="Creator provided timestamped drafts and portfolio history.">
        </label>
        <div class="actions" style="margin-top: 12px;">
          <button id="certificateBtn">Issue Certificate</button>
          <button class="secondary" id="certificatesBtn">View Certificates</button>
        </div>
      </section>

      <section>
        <h2>Image Metadata Support</h2>
        <p class="small">Analyze image-adjacent metadata as a second content type.</p>
        <div class="row" style="margin-top: 14px;">
          <label>Creator ID
            <input id="metadataCreatorId" value="creator_demo">
          </label>
          <label>Content ID
            <input id="metadataContentId" value="image_demo">
          </label>
        </div>
        <label style="margin-top: 12px;">Metadata JSON
          <textarea id="metadataJson" style="min-height: 130px;">{"tool":"Midjourney","prompt":"cinematic portrait, studio lighting","exif_present":false,"edit_history_present":false}</textarea>
        </label>
        <div class="actions" style="margin-top: 12px;">
          <button id="metadataBtn">Analyze Metadata</button>
        </div>
      </section>

      <section>
        <h2>Appeal a Decision</h2>
        <div class="row" style="margin-top: 14px;">
          <label>Decision ID
            <input id="appealDecisionId" placeholder="Filled after classification">
          </label>
          <label>Creator ID
            <input id="appealCreatorId" value="creator_demo">
          </label>
        </div>
        <label style="margin-top: 12px;">Reason
          <textarea id="appealReason" style="min-height: 90px;">This was my original draft and I want a human reviewer to check the edit history.</textarea>
        </label>
        <label style="margin-top: 12px;">Evidence
          <input id="appealEvidence" value="Draft notes and timestamped document history are available.">
        </label>
        <div class="actions" style="margin-top: 12px;">
          <button id="appealBtn">Submit Appeal</button>
          <button class="secondary" id="appealsBtn">View Appeals</button>
        </div>
      </section>
    </div>

    <aside class="stack">
      <section>
        <h2>Decision Summary</h2>
        <div class="metric-grid">
          <div class="metric"><strong>Label</strong><span id="label">-</span></div>
          <div class="metric"><strong>Confidence</strong><span id="confidence">-</span></div>
          <div class="metric"><strong>AI Likelihood</strong><span id="likelihood">-</span></div>
        </div>
        <div class="metric" style="margin-top: 10px;"><strong>Certificate</strong><span id="certificateLabel">-</span></div>
        <p class="small" id="recommendation" style="margin-top: 12px;">Run a classification to see the transparency label.</p>
      </section>

      <section>
        <h2>Analytics Dashboard</h2>
        <div class="metric-grid">
          <div class="metric"><strong>Decisions</strong><span id="totalDecisions">-</span></div>
          <div class="metric"><strong>Appeal Rate</strong><span id="appealRate">-</span></div>
          <div class="metric"><strong>Uncertain</strong><span id="uncertainRate">-</span></div>
        </div>
        <div class="metric-grid">
          <div class="metric"><strong>Avg Conf.</strong><span id="avgConfidence">-</span></div>
          <div class="metric"><strong>Verified</strong><span id="verifiedCreators">-</span></div>
          <div class="metric"><strong>Types</strong><span id="contentTypes">-</span></div>
        </div>
        <div class="actions" style="margin-top: 12px;">
          <button class="secondary" id="analyticsBtn">Refresh Analytics</button>
        </div>
      </section>

      <section>
        <h2>Home Repair Guardrail</h2>
        <label style="margin-top: 12px;">Question
          <textarea id="repairQuestion" style="min-height: 90px;">How do I replace a breaker in my electrical panel?</textarea>
        </label>
        <div class="actions" style="margin-top: 12px;">
          <button id="repairBtn">Check Safety</button>
        </div>
      </section>

      <section>
        <h2>API Response</h2>
        <pre class="result" id="output">Ready.</pre>
      </section>

      <section>
        <h2>Audit Snapshot</h2>
        <div class="result" id="auditSnapshot">Click Refresh Audit to load recent decision events.</div>
      </section>
    </aside>
  </main>

  <script>
    const output = document.querySelector("#output");
    const show = (data) => {
      output.textContent = typeof data === "string" ? data : JSON.stringify(data, null, 2);
    };
    const summarizeAudit = (events) => {
      if (!events.length) return "No audit events yet. Run Classify or Submit Appeal first.";
      return events.slice(-6).reverse().map((event) => {
        const kind = event.event_type || "event";
        const label = event.transparency_label || event.safety_label || event.status || "recorded";
        const id = event.decision_id || event.guardrail_id || event.appeal_id || event.event_id;
        return `${event.timestamp || "no timestamp"} | ${kind} | ${label} | ${id}`;
      }).join("\\n");
    };
    const requestJson = async (url, options = {}) => {
      const response = await fetch(url, {
        headers: { "Content-Type": "application/json", ...(options.headers || {}) },
        ...options
      });
      const data = await response.json();
      if (!response.ok) throw data;
      return data;
    };

    async function checkHealth() {
      try {
        const data = await requestJson("/health");
        document.querySelector("#health").textContent = `${data.service}: ${data.status}`;
      } catch (error) {
        document.querySelector("#health").textContent = "API unavailable";
        document.querySelector("#health").classList.add("warning");
      }
    }

    document.querySelector("#classifyBtn").addEventListener("click", async () => {
      try {
        const data = await requestJson("/classify", {
          method: "POST",
          body: JSON.stringify({
            creator_id: document.querySelector("#creatorId").value,
            content_id: document.querySelector("#contentId").value,
            content: document.querySelector("#content").value
          })
        });
        document.querySelector("#label").textContent = data.transparency_label;
        document.querySelector("#confidence").textContent = data.confidence;
        document.querySelector("#likelihood").textContent = data.ai_likelihood;
        document.querySelector("#recommendation").textContent = data.recommended_action;
        document.querySelector("#appealDecisionId").value = data.decision_id;
        document.querySelector("#appealCreatorId").value = data.creator_id;
        document.querySelector("#certificateLabel").textContent = data.provenance_certificate ? data.provenance_certificate.display_label : "No certificate";
        show(data);
      } catch (error) {
        show(error);
      }
    });

    document.querySelector("#certificateBtn").addEventListener("click", async () => {
      try {
        const data = await requestJson("/certificates", {
          method: "POST",
          body: JSON.stringify({
            creator_id: document.querySelector("#certCreatorId").value,
            verification_method: document.querySelector("#certMethod").value,
            evidence_summary: document.querySelector("#certEvidence").value
          })
        });
        document.querySelector("#certificateLabel").textContent = data.display_label;
        show(data);
      } catch (error) {
        show(error);
      }
    });

    document.querySelector("#metadataBtn").addEventListener("click", async () => {
      try {
        const metadata = JSON.parse(document.querySelector("#metadataJson").value);
        const data = await requestJson("/metadata/analyze", {
          method: "POST",
          body: JSON.stringify({
            creator_id: document.querySelector("#metadataCreatorId").value,
            content_id: document.querySelector("#metadataContentId").value,
            metadata
          })
        });
        document.querySelector("#label").textContent = data.transparency_label;
        document.querySelector("#confidence").textContent = data.confidence;
        document.querySelector("#likelihood").textContent = data.ai_likelihood;
        document.querySelector("#recommendation").textContent = data.recommended_action;
        document.querySelector("#appealDecisionId").value = data.decision_id;
        document.querySelector("#appealCreatorId").value = data.creator_id;
        document.querySelector("#certificateLabel").textContent = data.provenance_certificate ? data.provenance_certificate.display_label : "No certificate";
        show(data);
      } catch (error) {
        show(error instanceof SyntaxError ? { error: "metadata_json_invalid", message: error.message } : error);
      }
    });

    document.querySelector("#appealBtn").addEventListener("click", async () => {
      try {
        show(await requestJson("/appeals", {
          method: "POST",
          body: JSON.stringify({
            decision_id: document.querySelector("#appealDecisionId").value,
            creator_id: document.querySelector("#appealCreatorId").value,
            reason: document.querySelector("#appealReason").value,
            evidence: document.querySelector("#appealEvidence").value
          })
        }));
      } catch (error) {
        show(error);
      }
    });

    document.querySelector("#repairBtn").addEventListener("click", async () => {
      try {
        show(await requestJson("/home-repair/guardrail", {
          method: "POST",
          body: JSON.stringify({ question: document.querySelector("#repairQuestion").value })
        }));
      } catch (error) {
        show(error);
      }
    });

    document.querySelector("#auditBtn").addEventListener("click", async () => {
      const button = document.querySelector("#auditBtn");
      button.disabled = true;
      document.querySelector("#auditStatus").textContent = "Loading audit...";
      try {
        const data = await requestJson("/audit");
        const count = data.events ? data.events.length : 0;
        const loadedAt = new Date().toLocaleTimeString();
        document.querySelector("#auditStatus").textContent = `${count} events loaded at ${loadedAt}`;
        document.querySelector("#auditSnapshot").textContent = summarizeAudit(data.events || []);
        show(data);
      } catch (error) {
        document.querySelector("#auditStatus").textContent = "Audit load failed";
        document.querySelector("#auditSnapshot").textContent = JSON.stringify(error, null, 2);
        show(error);
      } finally {
        button.disabled = false;
      }
    });
    document.querySelector("#appealsBtn").addEventListener("click", async () => {
      try { show(await requestJson("/appeals")); } catch (error) { show(error); }
    });
    document.querySelector("#certificatesBtn").addEventListener("click", async () => {
      try { show(await requestJson("/certificates")); } catch (error) { show(error); }
    });
    document.querySelector("#analyticsBtn").addEventListener("click", async () => {
      try {
        const data = await requestJson("/analytics");
        document.querySelector("#totalDecisions").textContent = data.summary.total_decisions;
        document.querySelector("#appealRate").textContent = `${Math.round(data.summary.appeal_rate * 100)}%`;
        document.querySelector("#uncertainRate").textContent = `${Math.round(data.summary.uncertain_rate * 100)}%`;
        document.querySelector("#avgConfidence").textContent = data.summary.average_confidence;
        document.querySelector("#verifiedCreators").textContent = data.summary.verified_creators;
        document.querySelector("#contentTypes").textContent = Object.keys(data.by_content_type).join(", ") || "-";
        show(data);
      } catch (error) {
        show(error);
      }
    });
    checkHealth();
    document.querySelector("#analyticsBtn").click();
  </script>
</body>
</html>
"""
limiter = SlidingWindowRateLimiter(
    max_requests=int(os.getenv("PROVENANCE_GUARD_RATE_LIMIT", "10")),
    window_seconds=int(os.getenv("PROVENANCE_GUARD_RATE_WINDOW", "60")),
)
RATE_LIMITED_ENDPOINTS = {"classify", "submit_compatible"}


def create_app() -> Flask:
    app = Flask(__name__)

    @app.before_request
    def enforce_rate_limit() -> Any:
        if request.endpoint not in RATE_LIMITED_ENDPOINTS:
            return None
        key = request.headers.get("X-API-Key") or request.remote_addr or "anonymous"
        result = limiter.check(key)
        if result.allowed:
            request.rate_limit_remaining = result.remaining  # type: ignore[attr-defined]
            return None
        response = jsonify(
            {
                "error": "rate_limited",
                "message": "Too many requests. Slow down and retry after the cooldown window.",
                "retry_after_seconds": result.retry_after_seconds,
            }
        )
        response.status_code = 429
        response.headers["Retry-After"] = str(result.retry_after_seconds)
        return response

    @app.after_request
    def attach_rate_limit_headers(response: Any) -> Any:
        remaining = getattr(request, "rate_limit_remaining", None)
        if remaining is not None:
            response.headers["X-RateLimit-Remaining"] = str(remaining)
        return response

    @app.get("/health")
    def health() -> Any:
        return jsonify({"status": "ok", "service": "Provenance Guard"})

    @app.post("/classify")
    def classify() -> Any:
        payload = request.get_json(silent=True) or {}
        content = str(payload.get("content") or "").strip()
        creator_id = str(payload.get("creator_id") or "anonymous")
        content_id = str(payload.get("content_id") or new_id("content"))

        validation_error = _validate_content(content)
        if validation_error:
            return validation_error

        return jsonify(_classify_submission(content, creator_id, content_id, request.remote_addr))

    @app.post("/submit")
    def submit_compatible() -> Any:
        payload = request.get_json(silent=True) or {}
        content_type = str(payload.get("content_type") or "text").strip()
        creator_id = str(payload.get("creator_id") or "").strip()

        if not creator_id:
            return jsonify({"error": "Request must include 'creator_id'."}), 400

        if content_type == "image_metadata":
            metadata = payload.get("metadata")
            if not isinstance(metadata, dict):
                return jsonify({"error": "Request must include metadata object for image_metadata submissions."}), 400
            result = _classify_image_metadata(metadata, creator_id, new_id("content"), request.remote_addr)
            return jsonify(
                {
                    "content_id": result["content_id"],
                    "decision_id": result["decision_id"],
                    "content_type": result["content_type"],
                    "attribution": _legacy_attribution(result["classification"]),
                    "confidence": result["confidence"],
                    "ai_likelihood": result["ai_likelihood"],
                    "signal_scores": result["signals"],
                    "label": result["plain_language_label"],
                    "status": "classified",
                }
            )

        content = str(payload.get("text") or "").strip()
        validation_error = _validate_content(content, field_name="text")
        if validation_error:
            return validation_error

        result = _classify_submission(content, creator_id, new_id("content"), request.remote_addr)
        return jsonify(
            {
                "content_id": result["content_id"],
                "decision_id": result["decision_id"],
                "content_type": result["content_type"],
                "attribution": _legacy_attribution(result["classification"]),
                "confidence": result["confidence"],
                "ai_likelihood": result["ai_likelihood"],
                "signal_scores": {
                    signal["name"]: signal["score"]
                    for signal in result["signals"]
                },
                "label": result["plain_language_label"],
                "status": "classified",
            }
        )

    @app.post("/appeals")
    def create_appeal() -> Any:
        payload = request.get_json(silent=True) or {}
        decision_id = str(payload.get("decision_id") or "").strip()
        creator_id = str(payload.get("creator_id") or "").strip()
        reason = str(payload.get("reason") or "").strip()
        evidence = str(payload.get("evidence") or "").strip()

        missing = [
            field
            for field, value in {"decision_id": decision_id, "creator_id": creator_id, "reason": reason}.items()
            if not value
        ]
        if missing:
            return jsonify(
                {
                    "error": "validation_error",
                    "message": "Missing required appeal fields.",
                    "missing": missing,
                }
            ), 400

        appeal = {
            "appeal_id": new_id("appeal"),
            "decision_id": decision_id,
            "creator_id": creator_id,
            "reason": reason,
            "evidence": evidence,
            "status": "received",
            "next_step": "A reviewer should compare the original decision, creator context, and submitted evidence.",
            "created_at": utc_now(),
        }
        save_appeal(appeal)
        write_audit_event(
            "appeal_received",
            {
                "appeal_id": appeal["appeal_id"],
                "decision_id": decision_id,
                "creator_id": creator_id,
                "appeal_reasoning": reason,
                "evidence": evidence,
                "status": appeal["status"],
            },
        )
        return jsonify(appeal), 201

    @app.post("/appeal")
    def appeal_compatible() -> Any:
        payload = request.get_json(silent=True) or {}
        content_id = str(payload.get("content_id") or "").strip()
        reasoning = str(payload.get("creator_reasoning") or "").strip()

        if not content_id or not reasoning:
            return jsonify({"error": "Request must include 'content_id' and 'creator_reasoning'."}), 400

        original = _find_audit_decision(content_id=content_id)
        if not original:
            return jsonify({"error": "content_id not found"}), 404

        appeal = {
            "appeal_id": new_id("appeal"),
            "decision_id": original["decision_id"],
            "content_id": content_id,
            "creator_id": original.get("creator_id", "unknown"),
            "reason": reasoning,
            "evidence": "",
            "status": "under_review",
            "next_step": "A reviewer should compare the original decision, creator context, and submitted reasoning.",
            "created_at": utc_now(),
        }
        save_appeal(appeal)
        write_audit_event(
            "appeal_received",
            {
                "appeal_id": appeal["appeal_id"],
                "decision_id": appeal["decision_id"],
                "content_id": content_id,
                "creator_id": appeal["creator_id"],
                "appeal_reasoning": reasoning,
                "status": appeal["status"],
            },
        )
        return jsonify(
            {
                "message": "Appeal received. Your content has been flagged for human review.",
                "content_id": content_id,
                "decision_id": appeal["decision_id"],
                "status": "under_review",
            }
        )

    @app.post("/home-repair/guardrail")
    def home_repair_guardrail() -> Any:
        payload = request.get_json(silent=True) or {}
        question = str(payload.get("question") or "").strip()
        if not question:
            return jsonify({"error": "validation_error", "message": "`question` is required."}), 400

        result = assess_home_repair_question(question)
        guardrail_id = new_id("repair_guardrail")
        response_payload = {
            "guardrail_id": guardrail_id,
            "created_at": utc_now(),
            **result.to_dict(),
        }
        write_audit_event(
            "home_repair_guardrail_decision",
            {
                "guardrail_id": guardrail_id,
                "safety_label": result.safety_label,
                "should_answer": result.should_answer,
                "confidence": result.confidence,
                "matched_topics": result.matched_topics,
                "request_ip": request.remote_addr,
            },
        )
        return jsonify(response_payload)

    @app.post("/metadata/analyze")
    def analyze_metadata() -> Any:
        payload = request.get_json(silent=True) or {}
        metadata = payload.get("metadata")
        creator_id = str(payload.get("creator_id") or "anonymous")
        content_id = str(payload.get("content_id") or new_id("content"))
        if not isinstance(metadata, dict):
            return jsonify({"error": "validation_error", "message": "`metadata` object is required."}), 400
        return jsonify(_classify_image_metadata(metadata, creator_id, content_id, request.remote_addr))

    @app.post("/certificates")
    def create_certificate() -> Any:
        payload = request.get_json(silent=True) or {}
        creator_id = str(payload.get("creator_id") or "").strip()
        verification_method = str(payload.get("verification_method") or "").strip()
        evidence_summary = str(payload.get("evidence_summary") or "").strip()
        if not creator_id or not verification_method or not evidence_summary:
            return jsonify(
                {
                    "error": "validation_error",
                    "message": "`creator_id`, `verification_method`, and `evidence_summary` are required.",
                }
            ), 400

        certificate = {
            "certificate_id": new_id("cert"),
            "creator_id": creator_id,
            "status": "verified_human",
            "verification_method": verification_method,
            "evidence_summary": evidence_summary,
            "display_label": "Verified human creator",
            "created_at": utc_now(),
        }
        save_certificate(certificate)
        write_audit_event(
            "certificate_issued",
            {
                "certificate_id": certificate["certificate_id"],
                "creator_id": creator_id,
                "status": certificate["status"],
                "verification_method": verification_method,
            },
        )
        return jsonify(certificate), 201

    @app.get("/certificates")
    def list_certificates() -> Any:
        limit = _safe_limit(request.args.get("limit"))
        creator_id = request.args.get("creator_id")
        certificates = read_certificates(limit=limit)
        if creator_id:
            certificates = [certificate for certificate in certificates if certificate.get("creator_id") == creator_id]
        return jsonify({"certificates": certificates})

    @app.get("/appeals")
    def list_appeals() -> Any:
        limit = _safe_limit(request.args.get("limit"))
        return jsonify({"appeals": read_appeals(limit=limit)})

    @app.get("/audit")
    def list_audit_events() -> Any:
        limit = _safe_limit(request.args.get("limit"))
        return jsonify({"events": read_audit_events(limit=limit)})

    @app.get("/log")
    def log_compatible() -> Any:
        limit = _safe_limit(request.args.get("limit"))
        return jsonify({"entries": read_audit_events(limit=limit)})

    @app.get("/review-queue")
    def review_queue() -> Any:
        decisions = [
            event
            for event in read_audit_events(limit=250)
            if event.get("event_type") == "classification_decision"
            and (
                event.get("classification") == "uncertain"
                or float(event.get("confidence") or 0) < 0.55
            )
        ]
        appeals = read_appeals(limit=250)
        return jsonify(
            {
                "needs_review": decisions,
                "appeals": appeals,
                "summary": {
                    "uncertain_or_low_confidence_decisions": len(decisions),
                    "open_appeals": len(appeals),
                },
            }
        )

    @app.get("/analytics")
    def analytics() -> Any:
        return jsonify(_analytics_summary())

    @app.get("/")
    def index() -> Any:
        return INDEX_HTML

    @app.get("/api")
    def api_index() -> Any:
        return jsonify(
            {
                "service": "Provenance Guard",
                "endpoints": {
                    "health": "GET /health",
                    "classify": "POST /classify",
                    "appeals": "POST /appeals, GET /appeals",
                    "sample_compatible_submit": "POST /submit",
                    "sample_compatible_appeal": "POST /appeal",
                    "sample_compatible_log": "GET /log",
                    "audit": "GET /audit",
                    "review_queue": "GET /review-queue",
                    "analytics": "GET /analytics",
                    "certificates": "POST /certificates, GET /certificates",
                    "metadata": "POST /metadata/analyze",
                    "home_repair_guardrail": "POST /home-repair/guardrail",
                },
            }
        )

    return app


def _safe_limit(raw_value: str | None) -> int:
    try:
        return max(1, min(250, int(raw_value or "50")))
    except ValueError:
        return 50


def _validate_content(content: str, field_name: str = "content") -> Any | None:
    if not content:
        return jsonify({"error": "validation_error", "message": f"`{field_name}` is required."}), 400
    if len(content) > MAX_CONTENT_CHARS:
        return jsonify(
            {
                "error": "validation_error",
                "message": f"`{field_name}` must be {MAX_CONTENT_CHARS} characters or less.",
            }
        ), 400
    return None


def _classify_submission(content: str, creator_id: str, content_id: str, request_ip: str | None) -> dict[str, Any]:
    decision_id = new_id("decision")
    result = classify_content(content)
    content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    certificate = latest_certificate_for_creator(creator_id)
    response_payload = {
        "decision_id": decision_id,
        "content_id": content_id,
        "content_type": "text",
        "creator_id": creator_id,
        "content_hash": content_hash,
        "model_version": "heuristic-multisignal-v1",
        "created_at": utc_now(),
        **result.to_dict(),
        "plain_language_label": LABEL_COPY[result.classification],
        "provenance_certificate": certificate,
        "appeal": {
            "available": True,
            "endpoint": "/appeals",
            "required_fields": ["decision_id", "creator_id", "reason"],
        },
    }

    write_audit_event(
        "classification_decision",
        {
            "decision_id": decision_id,
            "content_id": content_id,
            "creator_id": creator_id,
            "content_hash": content_hash,
            "content_type": "text",
            "classification": result.classification,
            "attribution": _legacy_attribution(result.classification),
            "confidence": result.confidence,
            "ai_likelihood": result.ai_likelihood,
            "signal_scores": {signal.name: signal.score for signal in result.signals},
            "signals_used": [signal.name for signal in result.signals],
            "transparency_label": result.transparency_label,
            "plain_language_label": LABEL_COPY[result.classification],
            "certificate_id": certificate.get("certificate_id") if certificate else None,
            "status": "classified",
            "request_ip": request_ip,
        },
    )
    return response_payload


def _classify_image_metadata(
    metadata: dict[str, Any],
    creator_id: str,
    content_id: str,
    request_ip: str | None,
) -> dict[str, Any]:
    decision_id = new_id("decision")
    result = analyze_image_metadata(metadata)
    metadata_hash = hashlib.sha256(str(sorted(metadata.items())).encode("utf-8")).hexdigest()
    certificate = latest_certificate_for_creator(creator_id)
    response_payload = {
        "decision_id": decision_id,
        "content_id": content_id,
        "content_type": result.content_type,
        "creator_id": creator_id,
        "content_hash": metadata_hash,
        "model_version": "metadata-multisignal-v1",
        "created_at": utc_now(),
        **result.to_dict(),
        "plain_language_label": LABEL_COPY[result.classification],
        "provenance_certificate": certificate,
        "appeal": {
            "available": True,
            "endpoint": "/appeals",
            "required_fields": ["decision_id", "creator_id", "reason"],
        },
    }
    write_audit_event(
        "classification_decision",
        {
            "decision_id": decision_id,
            "content_id": content_id,
            "creator_id": creator_id,
            "content_hash": metadata_hash,
            "content_type": result.content_type,
            "classification": result.classification,
            "attribution": _legacy_attribution(result.classification),
            "confidence": result.confidence,
            "ai_likelihood": result.ai_likelihood,
            "signal_scores": result.signals,
            "signals_used": list(result.signals),
            "transparency_label": result.transparency_label,
            "plain_language_label": LABEL_COPY[result.classification],
            "certificate_id": certificate.get("certificate_id") if certificate else None,
            "status": "classified",
            "request_ip": request_ip,
        },
    )
    return response_payload


def _analytics_summary() -> dict[str, Any]:
    events = read_audit_events(limit=500)
    decisions = [event for event in events if event.get("event_type") == "classification_decision"]
    appeals = [event for event in events if event.get("event_type") == "appeal_received"]
    certificates = read_certificates(limit=500)

    by_classification: dict[str, int] = {}
    by_content_type: dict[str, int] = {}
    confidence_total = 0.0
    for decision in decisions:
        classification = str(decision.get("classification") or "unknown")
        content_type = str(decision.get("content_type") or "text")
        by_classification[classification] = by_classification.get(classification, 0) + 1
        by_content_type[content_type] = by_content_type.get(content_type, 0) + 1
        confidence_total += float(decision.get("confidence") or 0)

    uncertain_count = by_classification.get("uncertain", 0)
    total_decisions = len(decisions)
    appeal_rate = round(len(appeals) / total_decisions, 3) if total_decisions else 0.0
    uncertain_rate = round(uncertain_count / total_decisions, 3) if total_decisions else 0.0
    average_confidence = round(confidence_total / total_decisions, 3) if total_decisions else 0.0

    return {
        "summary": {
            "total_decisions": total_decisions,
            "open_appeals": len(appeals),
            "appeal_rate": appeal_rate,
            "uncertain_rate": uncertain_rate,
            "average_confidence": average_confidence,
            "verified_creators": len(certificates),
        },
        "by_classification": by_classification,
        "by_content_type": by_content_type,
        "recent_decisions": decisions[-6:],
        "recent_appeals": appeals[-6:],
    }


def _legacy_attribution(classification: str) -> str:
    return {
        "likely_ai_generated": "likely_ai",
        "likely_human_written": "likely_human",
        "uncertain": "uncertain",
    }.get(classification, "uncertain")


def _find_audit_decision(content_id: str) -> dict[str, Any] | None:
    for event in reversed(read_audit_events(limit=250)):
        if event.get("event_type") == "classification_decision" and event.get("content_id") == content_id:
            return event
    return None


app = create_app()


if __name__ == "__main__":
    port = int(os.getenv("PORT", "5010"))
    app.run(host=os.getenv("HOST", "0.0.0.0"), port=port)
