from __future__ import annotations

import json
import os
from typing import Any

import gradio as gr

from audit import (
    latest_certificate_for_creator,
    new_id,
    read_appeals,
    read_audit_events,
    read_certificates,
    save_appeal,
    save_certificate,
    utc_now,
    write_audit_event,
)
from detector import classify_content
from home_repair import assess_home_repair_question
from multimodal import analyze_image_metadata


LABEL_COPY = {
    "likely_ai_generated": (
        "Our system found strong indicators that this content may have been generated by an AI writing tool. "
        "This is not a final accusation and no creator penalty should be applied without review. "
        "If you wrote this yourself, submit an appeal with context about your drafting process."
    ),
    "uncertain": (
        "Our system was not able to confidently determine whether this content was written by a person or an AI tool. "
        "No automated action should be taken. A human reviewer should consider the context before applying a label."
    ),
    "likely_human_written": (
        "Our system found stronger indicators that this content was written by a person. "
        "No AI-generated content label is recommended."
    ),
}


def pretty(payload: Any) -> str:
    return json.dumps(payload, indent=2, sort_keys=True)


def classify_text(content: str, creator_id: str, content_id: str) -> tuple[str, str, float, float, str]:
    content = (content or "").strip()
    creator_id = (creator_id or "anonymous").strip()
    content_id = (content_id or new_id("content")).strip()
    if not content:
        return "Validation error", "Content is required.", 0.0, 0.0, pretty({"error": "content_required"})

    decision_id = new_id("decision")
    result = classify_content(content)
    certificate = latest_certificate_for_creator(creator_id)
    event = write_audit_event(
        "classification_decision",
        {
            "decision_id": decision_id,
            "content_id": content_id,
            "creator_id": creator_id,
            "content_type": "text",
            "classification": result.classification,
            "confidence": result.confidence,
            "ai_likelihood": result.ai_likelihood,
            "signal_scores": {signal.name: signal.score for signal in result.signals},
            "signals_used": [signal.name for signal in result.signals],
            "transparency_label": result.transparency_label,
            "plain_language_label": LABEL_COPY[result.classification],
            "certificate_id": certificate.get("certificate_id") if certificate else None,
            "status": "classified",
        },
    )
    payload = {
        "decision_id": decision_id,
        "content_id": content_id,
        "creator_id": creator_id,
        "classification": result.classification,
        "transparency_label": result.transparency_label,
        "plain_language_label": LABEL_COPY[result.classification],
        "confidence": result.confidence,
        "ai_likelihood": result.ai_likelihood,
        "recommended_action": result.recommended_action,
        "warnings": result.warnings,
        "signals": [signal.to_dict() for signal in result.signals],
        "provenance_certificate": certificate,
        "audit_event_id": event["event_id"],
    }
    certificate_text = certificate["display_label"] if certificate else "No verified-human certificate"
    return result.transparency_label, result.recommended_action, result.confidence, result.ai_likelihood, pretty(payload | {"certificate": certificate_text})


def submit_appeal(decision_id: str, creator_id: str, reason: str, evidence: str) -> str:
    decision_id = (decision_id or "").strip()
    creator_id = (creator_id or "").strip()
    reason = (reason or "").strip()
    evidence = (evidence or "").strip()
    if not decision_id or not creator_id or not reason:
        return pretty({"error": "decision_id, creator_id, and reason are required"})

    appeal = {
        "appeal_id": new_id("appeal"),
        "decision_id": decision_id,
        "creator_id": creator_id,
        "reason": reason,
        "evidence": evidence,
        "status": "under_review",
        "next_step": "A human reviewer should compare the original decision, signal scores, and creator evidence.",
        "created_at": utc_now(),
    }
    save_appeal(appeal)
    audit = write_audit_event(
        "appeal_received",
        {
            "appeal_id": appeal["appeal_id"],
            "decision_id": decision_id,
            "creator_id": creator_id,
            "appeal_reasoning": reason,
            "evidence": evidence,
            "status": appeal["status"],
        },
    )
    return pretty({"appeal": appeal, "audit_event": audit})


def issue_certificate(creator_id: str, verification_method: str, evidence_summary: str) -> str:
    creator_id = (creator_id or "").strip()
    verification_method = (verification_method or "").strip()
    evidence_summary = (evidence_summary or "").strip()
    if not creator_id or not verification_method or not evidence_summary:
        return pretty({"error": "creator_id, verification_method, and evidence_summary are required"})

    certificate = {
        "certificate_id": new_id("cert"),
        "creator_id": creator_id,
        "status": "verified_human",
        "verification_method": verification_method,
        "evidence_summary": evidence_summary,
        "display_label": "Verified human creator",
        "created_at": utc_now(),
    }
    save_certificate(certificate)
    audit = write_audit_event(
        "certificate_issued",
        {
            "certificate_id": certificate["certificate_id"],
            "creator_id": creator_id,
            "status": certificate["status"],
            "verification_method": verification_method,
        },
    )
    return pretty({"certificate": certificate, "audit_event": audit})


def analyze_metadata(metadata_json: str, creator_id: str, content_id: str) -> tuple[str, str, float, float, str]:
    try:
        metadata = json.loads(metadata_json or "{}")
    except json.JSONDecodeError as exc:
        return "Invalid metadata JSON", str(exc), 0.0, 0.0, pretty({"error": "invalid_json", "message": str(exc)})
    if not isinstance(metadata, dict):
        return "Invalid metadata JSON", "Metadata must be a JSON object.", 0.0, 0.0, pretty({"error": "metadata_must_be_object"})

    creator_id = (creator_id or "anonymous").strip()
    content_id = (content_id or new_id("content")).strip()
    decision_id = new_id("decision")
    result = analyze_image_metadata(metadata)
    certificate = latest_certificate_for_creator(creator_id)
    audit = write_audit_event(
        "classification_decision",
        {
            "decision_id": decision_id,
            "content_id": content_id,
            "creator_id": creator_id,
            "content_type": result.content_type,
            "classification": result.classification,
            "confidence": result.confidence,
            "ai_likelihood": result.ai_likelihood,
            "signal_scores": result.signals,
            "signals_used": list(result.signals),
            "transparency_label": result.transparency_label,
            "plain_language_label": LABEL_COPY[result.classification],
            "certificate_id": certificate.get("certificate_id") if certificate else None,
            "status": "classified",
        },
    )
    payload = result.to_dict() | {
        "decision_id": decision_id,
        "content_id": content_id,
        "creator_id": creator_id,
        "plain_language_label": LABEL_COPY[result.classification],
        "provenance_certificate": certificate,
        "audit_event_id": audit["event_id"],
    }
    return result.transparency_label, result.recommended_action, result.confidence, result.ai_likelihood, pretty(payload)


def home_repair(question: str) -> str:
    result = assess_home_repair_question(question or "")
    audit = write_audit_event(
        "home_repair_guardrail_decision",
        {
            "guardrail_id": new_id("repair_guardrail"),
            "safety_label": result.safety_label,
            "should_answer": result.should_answer,
            "confidence": result.confidence,
            "matched_topics": result.matched_topics,
        },
    )
    return pretty(result.to_dict() | {"audit_event_id": audit["event_id"]})


def analytics() -> str:
    events = read_audit_events(limit=500)
    decisions = [event for event in events if event.get("event_type") == "classification_decision"]
    appeals = [event for event in events if event.get("event_type") == "appeal_received"]
    certificates = read_certificates(limit=500)
    by_classification: dict[str, int] = {}
    by_content_type: dict[str, int] = {}
    confidence_total = 0.0
    for decision in decisions:
        classification = str(decision.get("classification") or "unknown")
        content_type = str(decision.get("content_type") or "text")
        by_classification[classification] = by_classification.get(classification, 0) + 1
        by_content_type[content_type] = by_content_type.get(content_type, 0) + 1
        confidence_total += float(decision.get("confidence") or 0)
    total_decisions = len(decisions)
    payload = {
        "summary": {
            "total_decisions": total_decisions,
            "open_appeals": len(appeals),
            "appeal_rate": round(len(appeals) / total_decisions, 3) if total_decisions else 0.0,
            "uncertain_rate": round(by_classification.get("uncertain", 0) / total_decisions, 3) if total_decisions else 0.0,
            "average_confidence": round(confidence_total / total_decisions, 3) if total_decisions else 0.0,
            "verified_creators": len(certificates),
        },
        "by_classification": by_classification,
        "by_content_type": by_content_type,
        "recent_events": events[-8:],
    }
    return pretty(payload)


with gr.Blocks(title="Provenance Guard") as demo:
    gr.Markdown(
        """
        # Provenance Guard
        AI attribution safety dashboard for creative platforms. This demo uses local, deterministic signals only.
        **No Groq or OpenAI API keys are used in this version.**
        """
    )

    with gr.Tab("Classify Text"):
        with gr.Row():
            creator_id = gr.Textbox(value="creator_demo", label="Creator ID")
            content_id = gr.Textbox(value="post_demo", label="Content ID")
        content = gr.Textbox(
            value=(
                "Furthermore, it is important to note that a robust and seamless platform can leverage modern workflows. "
                "Moreover, the solution provides a structured approach for teams seeking consistent outcomes. "
                "Additionally, the process can be adapted across contexts while maintaining clarity and efficiency. "
                "In conclusion, this comprehensive method supports scalable collaboration and measurable improvements."
            ),
            label="Submitted Content",
            lines=7,
        )
        classify_button = gr.Button("Classify")
        with gr.Row():
            label = gr.Textbox(label="Transparency Label")
            action = gr.Textbox(label="Recommended Action")
        with gr.Row():
            confidence = gr.Number(label="Confidence")
            likelihood = gr.Number(label="AI Likelihood")
        classify_output = gr.Code(label="Full Classification Response", language="json")
        classify_button.click(classify_text, [content, creator_id, content_id], [label, action, confidence, likelihood, classify_output])

    with gr.Tab("Appeals"):
        appeal_decision = gr.Textbox(label="Decision ID")
        appeal_creator = gr.Textbox(value="creator_demo", label="Creator ID")
        appeal_reason = gr.Textbox(value="This was my original draft and I can provide edit history.", label="Reason", lines=3)
        appeal_evidence = gr.Textbox(value="Timestamped drafts are available.", label="Evidence")
        appeal_button = gr.Button("Submit Appeal")
        appeal_output = gr.Code(label="Appeal Response", language="json")
        appeal_button.click(submit_appeal, [appeal_decision, appeal_creator, appeal_reason, appeal_evidence], appeal_output)

    with gr.Tab("Certificates"):
        cert_creator = gr.Textbox(value="creator_demo", label="Creator ID")
        cert_method = gr.Textbox(value="draft history + profile review", label="Verification Method")
        cert_evidence = gr.Textbox(value="Creator provided timestamped drafts and portfolio history.", label="Evidence Summary")
        cert_button = gr.Button("Issue Verified-Human Certificate")
        cert_output = gr.Code(label="Certificate Response", language="json")
        cert_button.click(issue_certificate, [cert_creator, cert_method, cert_evidence], cert_output)

    with gr.Tab("Image Metadata"):
        metadata_creator = gr.Textbox(value="creator_demo", label="Creator ID")
        metadata_content = gr.Textbox(value="image_demo", label="Content ID")
        metadata_json = gr.Textbox(
            value='{"tool":"Midjourney","prompt":"cinematic portrait, studio lighting","exif_present":false,"edit_history_present":false}',
            label="Image Metadata JSON",
            lines=5,
        )
        metadata_button = gr.Button("Analyze Metadata")
        with gr.Row():
            metadata_label = gr.Textbox(label="Transparency Label")
            metadata_action = gr.Textbox(label="Recommended Action")
        with gr.Row():
            metadata_confidence = gr.Number(label="Confidence")
            metadata_likelihood = gr.Number(label="AI Likelihood")
        metadata_output = gr.Code(label="Metadata Analysis Response", language="json")
        metadata_button.click(
            analyze_metadata,
            [metadata_json, metadata_creator, metadata_content],
            [metadata_label, metadata_action, metadata_confidence, metadata_likelihood, metadata_output],
        )

    with gr.Tab("Safety Guardrail"):
        repair_question = gr.Textbox(value="How do I replace a breaker in my electrical panel?", label="Home Repair Question", lines=3)
        repair_button = gr.Button("Check Safety")
        repair_output = gr.Code(label="Guardrail Response", language="json")
        repair_button.click(home_repair, repair_question, repair_output)

    with gr.Tab("Analytics / Audit"):
        analytics_button = gr.Button("Refresh Analytics")
        analytics_output = gr.Code(label="Analytics And Recent Audit Events", language="json")
        analytics_button.click(analytics, outputs=analytics_output)


if __name__ == "__main__":
    port = int(os.getenv("GRADIO_SERVER_PORT", "7864"))
    demo.launch(server_name="0.0.0.0", server_port=port, share=True)
