from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any


AI_TOOL_HINTS = {
    "chatgpt",
    "dall-e",
    "dalle",
    "midjourney",
    "stable diffusion",
    "firefly",
    "runway",
    "sora",
    "gemini",
}

PROMPT_HINTS = {
    "prompt",
    "negative prompt",
    "seed",
    "cfg scale",
    "sampler",
    "model checkpoint",
    "generated by",
    "text-to-image",
}

HUMAN_EVIDENCE_HINTS = {
    "camera",
    "lens",
    "exif",
    "contact sheet",
    "raw file",
    "sketch",
    "draft",
    "behind the scenes",
}


@dataclass(frozen=True)
class MetadataAnalysisResult:
    content_type: str
    classification: str
    confidence: float
    ai_likelihood: float
    transparency_label: str
    recommended_action: str
    signals: dict[str, float]
    rationale: list[str]

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def analyze_image_metadata(metadata: dict[str, Any]) -> MetadataAnalysisResult:
    """Classify image-adjacent metadata without inspecting pixels.

    This is intentionally a metadata support path, not a claim that the system can
    detect generated images from the image itself.
    """
    text = " ".join(str(value).lower() for value in metadata.values() if value is not None)
    tool_hits = sum(1 for hint in AI_TOOL_HINTS if hint in text)
    prompt_hits = sum(1 for hint in PROMPT_HINTS if hint in text)
    human_hits = sum(1 for hint in HUMAN_EVIDENCE_HINTS if hint in text)

    exif_present = bool(metadata.get("exif_present"))
    edit_history_present = bool(metadata.get("edit_history_present") or metadata.get("draft_history_present"))
    source_file_type = str(metadata.get("source_file_type") or "").lower()
    raw_file_bonus = 1 if source_file_type in {"raw", "dng", "cr2", "nef", "arw"} else 0

    signals = {
        "generator_tool_mentions": min(tool_hits / 2, 1.0),
        "prompt_artifacts": min(prompt_hits / 3, 1.0),
        "missing_camera_metadata": 0.0 if exif_present else 0.65,
        "human_creation_evidence": max(0.0, 1.0 - min((human_hits + raw_file_bonus + int(edit_history_present)) / 3, 1.0)),
    }
    ai_likelihood = max(0.0, min(1.0, sum(signals.values()) / len(signals)))
    evidence_strength = min(1.0, (tool_hits + prompt_hits + human_hits + int(exif_present) + int(edit_history_present)) / 6)
    confidence = round(max(0.35, min(0.92, abs(ai_likelihood - 0.5) + evidence_strength * 0.45)), 3)

    if confidence < 0.55 or 0.38 <= ai_likelihood <= 0.62:
        classification = "uncertain"
        transparency_label = "Needs metadata review"
        recommended_action = "Ask for source files, edit history, or creator process evidence before applying a label."
    elif ai_likelihood > 0.62:
        classification = "likely_ai_generated"
        transparency_label = "Likely AI-generated metadata"
        recommended_action = "Show an AI-content label unless the creator provides stronger provenance evidence."
    else:
        classification = "likely_human_written"
        transparency_label = "Likely human-created metadata"
        recommended_action = "No generated-content label recommended; preserve the audit trail."

    rationale = []
    if tool_hits:
        rationale.append("Metadata mentions known generative tools.")
    if prompt_hits:
        rationale.append("Metadata contains prompt or generation-parameter artifacts.")
    if exif_present or raw_file_bonus:
        rationale.append("Camera/source-file evidence lowers generated-content likelihood.")
    if edit_history_present:
        rationale.append("Edit or draft history supports a human provenance path.")
    if not rationale:
        rationale.append("Metadata is sparse, so the system avoids a confident attribution.")

    return MetadataAnalysisResult(
        content_type="image_metadata",
        classification=classification,
        confidence=confidence,
        ai_likelihood=round(ai_likelihood, 3),
        transparency_label=transparency_label,
        recommended_action=recommended_action,
        signals={name: round(score, 3) for name, score in signals.items()},
        rationale=rationale,
    )
